import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Navbar";
import AuthProvider from "@/components/Provider";

export const metadata: Metadata = {
  title: "NextBlog",
  description: "NextBlog is Generated by next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased bg-lightBg dark:bg-darkBg ">
        <AuthProvider>
          <Navbar />
          <main className="flex-1 my-8 w-full max-w-7xl mx-auto px-4">
            {children}
          </main>
        </AuthProvider>
      </body>
    </html>
  );
}
